apiVersion: v1
kind: Service
metadata:
  name: netbirdapp
spec:
  selector:
    app: netbirdapp
  type: ClusterIP
  ports:
    - name: netbirdapp
      protocol: TCP
      port: 80
      targetPort: 80
---

